name: iOS Package CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build
        run: |
          xcodebuild \
            -scheme YettelSpeedSDK \
            -destination 'generic/platform=iOS' \
            -skipPackagePluginValidation \
            build
      - name: Test
        run: |
          xcodebuild \
            -scheme YettelSpeedSDK \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -skipPackagePluginValidation \
            test
